package uz.pdp.cascade_types_annotatsiyalar.entity.enums;

public enum UssdCodsName {

  SEND_SMS, CALL, USE_INTERNET, USER_INFO_ENTERTAINMENT, FILL_BALANCE,
  BUY_PACKAGE, CHANGE_TARIFF, CHECK_TARIFF, ACTIVATE_TARIFF, BUY_INFO_ENTERTAINMENT,

}
